# Site settings
title: Tiny Galaxy - Gateway to knowledge
description: "  Tiny Galaxy at Amstelveen, is a special plce where children's unique thinking flourishes. We are made up of experienced facilitators who believe in the importance of developmentally appropriate practices, hands-on learning, arts exposure and social guidance for the youngest of people under age of 4 years.
."
baseurl: "/Home" # the subpath of your site, e.g. /blog
url: "tinygalaxy.nl" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Tiny Galaxy
    hero_description: Gateway to knowledge!!
    
# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +31 (0) 645110505
    email: tinygalaxyamstelveen@gmail.com
    address: C/o Muziel and Dandsschool, Stadsplein 99 1181ZM Amstelveen. Located at 2nd floor, room number 8

# Opening hours
Mon_Tue_Thus: 10:00 AM – 12:30 PM
Wedn: 10:00 AM – 12:00 PM

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Stadsplein 99, 1181ZMm Amstelveen, Netherlands
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com/tinygalaxy2017
instagram: http://instagram.com
youtube: http://youtube.com
feed: yes

# Footer
copyright: © 2019 Tiny Galaxy Amstelveen - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
